version: '3'

services:
  db:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: hobbies-app
      POSTGRES_PASSWORD: hobbies-password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - default

  rest-api:
    image: ryangst1/hobbies-api
    restart: unless-stopped
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: hobbies-app
      SPRING_DATASOURCE_PASSWORD: hobbies-password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: true
    networks:
      - default
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount to store certificates
      - /var/www/certbot:/var/www/certbot   # Webroot for certbot challenge
    networks:
      - default
    depends_on:
      - rest-api

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # Mount to store certificates
      - /var/www/certbot:/var/www/certbot   # Webroot for certbot challenge
    entrypoint: "/bin/sh"
    networks:
      - default

networks:
  default:
    driver: bridge
