spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: hobbies-app
    password: hobbies-password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
