CREATE SEQUENCE IF NOT EXISTS person_id_seq INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS person
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address    VARCHAR(255),
    first_name VARCHAR(255)                            NOT NULL,
    gender     VARCHAR(255),
    last_name  VARCHAR(255)                            NOT NULL,
    CONSTRAINT person_pkey PRIMARY KEY (id)
);
