CREATE TABLE book
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    author      VARCHAR(255)                            NOT NULL,
    price       DOUBLE PRECISION                        NOT NULL,
    launch_date VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);
