name: Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      -
        name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      -
        name: Build Application Jar
        run: mvn clean package
      -
        name: Build Docker Image
        run: docker compose build

      - name: Push Docker Image
        run: |
          docker tag ${{ github.repository }}:latest ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
          docker tag ${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.run_id }}
