name: Push Docker Image to GitHub Container Registry

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      -
        name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      -
        name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      -
        name: Build Application Jar
        run: mvn clean package
      -
        name: Build Docker Image
        run: docker compose build

      - name: Push Docker Image
        run: |
            docker tag ${{ secrets.DOCKER_USERNAME }}/hobbies-api:latest ${{ secrets.DOCKER_USERNAME }}/hobbies-api:${{github.run_id}}
            docker push ${{ secrets.DOCKER_USERNAME }}/hobbies-api:${{github.run_id}}
            docker push ${{ secrets.DOCKER_USERNAME }}/hobbies-api:latest

      - name: SSH to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pwd
            cd /root/hobbies
            docker compose down
            docker compose pull
            docker compose up -d
