name: Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      -
        name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      -
        name: Build Application Jar
        uses: actions/checkout@v3
        run: mvn clean package
      -
        name: Build Docker Image
        run: docker compose build

      - name: Push Docker Image
        run: |
          docker tag ryangst1/hobbies-api:latest ghcr.io/ryangst1/hobbies-api:latest
          docker push ghcr.io/ryangst1/hobbies-api:${{ github.run_id }}
          docker push ghcr.io/ryangst1/hobbies-api:latest
